apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cd-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: cd-apps
    repoURL: 'https://github.com/j3k4/k8s-openlab'
    targetRevision: temp
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
