
alertmanager:
  enabled: false
  ingress:
    enabled: true
    hosts: 
    - alarm.sva.lab
    path: /
grafana:
  enabled: true
  ingress:
    enabled: true
    hosts: 
    - grafana.sva.lab
    path: /
prometheus:
  enabled: true
  ingress:
    enabled: true
    hosts: 
    - prom.sva.lab
    path: /
