---
name: Pull Request Check

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate manifests
        uses: makocchi-git/actions-k8s-manifests-validate-kubeval@1.0.0
        with:
          files: cd-apps,apps
          token: ${{ secrets.GITHUB_TOKEN }}