---
name: Pull Request Check

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate manifests
        uses: azure/k8s-lint@v1
        with:
          manifests: |
              cd-apps/*.yaml
              apps/**/*.yaml