---
name: Pull Request Check

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: validate manifests
        uses: yokawasa/action-setup-kube-tools@v0.9.2